### ISSUE TITLE
MOODLE_32_STABLE requires unavailable version of local_eliscore

### ISSUE THREAD

**Issue by frederickOtus** [remotelearner/moodle-local_datahub#1]
The MOODLE_32_STABLE branch currently requires local_eliscore version 2016120501.

https://github.com/remotelearner/moodle-local_datahub/blob/MOODLE_32_STABLE/verson.php

Currently, there is no available version of local_eliscore that satisfies that requirement.

**Comment by jamesmcq** [comment]
@frederickOtus This should now be available in https://github.com/remotelearner/moodle-local_eliscore branch MOODLE_32_STABLE. Thanks for the head's up!
